services:
  db:
    image: postgres:16.8-alpine3.21
    environment:
      - POSTGRES_PASSWORD=postgres
  app:
    image: tolgee/tolgee
    ports:
      - "8090:8080"
    env_file:
      - .env
    depends_on:
      - "db"
